global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'litellm'
    metrics_path: '/metrics/'
    static_configs:
      - targets: ['coreai_litellm:4000']

  - job_name: 'infinity'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['coreai_infinity:8080']