apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    # URL interna de la red de Docker
    url: http://coreai_prometheus:9090
    access: proxy
    isDefault: true
    editable: false

  - name: Loki
    type: loki
    # URL interna de la red de Docker
    url: http://coreai_loki:3100
    access: proxy
    editable: false